### ISSUE TITLE
Error Can't select the Proxy Settings 

### ISSUE THREAD

**Issue by masbog** [summitt/Burp-Non-HTTP-Extension#23]
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
	at josh.ui.NonHttpUI$11.tableChanged(NonHttpUI.java:606)
	at javax.swing.table.AbstractTableModel.fireTableChanged(AbstractTableModel.java:296)
	at javax.swing.table.AbstractTableModel.fireTableCellUpdated(AbstractTableModel.java:275)
	at javax.swing.table.DefaultTableModel.setValueAt(DefaultTableModel.java:666)
	at javax.swing.JTable.setValueAt(JTable.java:2741)
	at javax.swing.JTable.editingStopped(JTable.java:4723)
	at javax.swing.AbstractCellEditor.fireEditingStopped(AbstractCellEditor.java:141)
	at javax.swing.DefaultCellEditor$EditorDelegate.stopCellEditing(DefaultCellEditor.java:368)
	at javax.swing.DefaultCellEditor.stopCellEditing(Def

**Comment by summitt** [comment]
Thanks i'm aware of the issue. I have it mitigated in my most recent release but have not had time to finish it lately. Usually a restart is required as a work around.

**Comment by masbog** [comment]
yes, because i can't choose the option from table... restart burp is the best choice right now... 😄

**Comment by molitona** [comment]
@masbog @summitt 
I'm following FB guide to configure FB Lite app to be proxied through burp (https://www.facebook.com/whitehat/education/testing-guides)

I've a problem that is the proxy can't be enabled even though burp isn't listening on port 443.

![2021-09-03_15-09](https://user-images.githubusercontent.com/35532337/132019262-5fd9c71b-862d-42b3-aefa-035cd9b88d5f.png)

Any help, please !
