### ISSUE TITLE
port monitor isnt working 

### ISSUE THREAD

**Issue by haythom77** [summitt/Burp-Non-HTTP-Extension#24]
hi sir
i configured dns and get dns history but port monitor isnt working 
and interception isnt working

**Comment by summitt** [comment]
Check that you have wireshark installed first. Though i was working with someone a few weeks ago that was having a similar problem.

**Comment by lazyjohny500** [comment]
I have the same problem. and I have Wireshark installed...

**Comment by adirkuhn** [comment]
Port monitor is not working for me also with the current stable version and also with v.1.7.15

I start the burp app as root, add the Nope extension but when I try to start the Port Monitor I got this message

```
Lister Started
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
```

**Comment by hack2012** [comment]
I have the same problem

> Lister Started
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.lang.UnsatisfiedLinkError: Unable to load library 'wpcap': Native library (win32-x86-64/wpcap.dll) not found in resource path ([sss])
        at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:277)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:403)
        at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:342)
        at com.sun.jna.Function.getFunction(Function.java:82)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:42)
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:51)
        at org.pcap4j.core.Pcaps.getDevByAddress(Pcaps.java:98)
        at josh.utils.Lister.run(Lister.java:55)
        at java.lang.Thread.run(Unknown Source)

**Comment by hack2012** [comment]
I have solved the problem. 
I resinstalled `nmap-7.80-setup.exe`  and selected the option of   `Install Npcap in winpcap api-compatible mode`

**Comment by summitt** [comment]
A fix for this has been pushed [here](https://github.com/summitt/Burp-Non-HTTP-Extension/commit/2c2e1830ec8fec772bf4ee62c34ae35588a6ac6e#diff-5ab9fac41fd253f8b75152a9a8c57f8fa114e4b6844fcfe1e4f5a685b48f2d26)
