### ISSUE TITLE
Could not run extention in burp.

### ISSUE THREAD

**Issue by Abiral1** [summitt/Burp-Non-HTTP-Extension#3]
How do I run this extension in burp ? I tried adding  on adding burpextender.java in burp extender tab but I get following error:

> java.lang.ClassNotFoundException: burp.BurpExtender
	at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:274)
	at burp.poe.a(Unknown Source)
	at burp.poe.<init>(Unknown Source)
	at burp.prg.a(Unknown Source)
	at burp.hdc.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:745)

**Comment by summitt** [comment]
are you on Mac, pc, or Linux?

**Comment by summitt** [comment]
ohh.i see what you did. you need to download the latest jar file from the releases section. it will be called NopeProxy.jar. https://github.com/summitt/Burp-Non-HTTP-Extension/releases

**Comment by bhatnagarakshat197** [comment]
I was trying to add Burplay extension but getting the same error as mentioned in the first comment. Trying to access in on PC (Windows 10).
