### ISSUE TITLE
Plugin not working keeps getting nullpointers

### ISSUE THREAD

**Issue by yoyo00xx** [summitt/Burp-Non-HTTP-Extension#45]
java.lang.NullPointerException
        at josh.utils.Lister$1.gotPacket(Lister.java:70)
        at org.pcap4j.core.PcapHandle$GotPacketFuncExecutor.lambda$got_packet$0(PcapHandle.java:1254)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:832)

The above is the stack trace I dont know what to do is there like a specific pcap version or configuration i need to have?

Am running windows 10

**Comment by yoyo00xx** [comment]
Also initially this is thrown out

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
MLog initialization issue: slf4j found no binding or threatened to use its (dangerously silent) NOPLogger. We consider the slf4j library not found.

**Comment by yoyo00xx** [comment]
is there a way i can add it manaully?

**Comment by summitt** [comment]
Just released a new version that can b downloaded in Releases.
