### ISSUE TITLE
Port monitoring - Error description for Linux(Kali)

### ISSUE THREAD

**Issue by rbk0** [summitt/Burp-Non-HTTP-Extension#56]
Activating Port monitoring results in the following error message:

`Lister Started
java.lang.ExceptionInInitializerError
        at org.pcap4j.core.Pcaps.findAllDevs(Pcaps.java:56)
        at org.pcap4j.core.Pcaps.getDevByAddress(Pcaps.java:99)
        at josh.utils.Lister.run(Lister.java:56)
        at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.NullPointerException
        at java.base/java.util.Objects.requireNonNull(Objects.java:208)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:260)
        at java.base/java.nio.file.Path.of(Path.java:147)
        at java.base/java.nio.file.Paths.get(Paths.java:69)
        at org.pcap4j.core.NativeMappings.<clinit>(NativeMappings.java:46)
        ... 4 more
`
Could not afford to further trace the origin for now.

Some more info:
- NoPE 1.6
- running as root on
- Kali 2021.1 (kali-rolling)
- Burp Pro v2021.9.1 (openjdk 16.0.2 2021-07-20)
- libpcap0.8 Version:1.10.1-4

Anyone else having same issue for similar environment or is this a problem in a general?

**Comment by molitona** [comment]
@rbk0 
You solved it ?? what app traffic you're trying to intercept ?

**Comment by summitt** [comment]
A fix for this has been pushed [here](https://github.com/summitt/Burp-Non-HTTP-Extension/commit/2c2e1830ec8fec772bf4ee62c34ae35588a6ac6e#diff-5ab9fac41fd253f8b75152a9a8c57f8fa114e4b6844fcfe1e4f5a685b48f2d26)
