### ISSUE TITLE
M1 MacBook Pro does not get the NoPE Proxy Tab

### ISSUE THREAD

**Issue by oliv10** [summitt/Burp-Non-HTTP-Extension#63]
When using an M1 MacBook the tab for NoPE Proxy does not show up at all.

**Comment by summitt** [comment]
I'm not having this issue on my M1. Can you provide any additional detail.

**Comment by kgmhk** [comment]
Me too.

Here is error msg

```
java.lang.NullPointerException: Cannot read field "ntbm" because "this.dnsConfig" is null
	at burp.BurpExtender.shouldShow(BurpExtender.java:155)
	at burp.BurpExtender.createMenuItems(BurpExtender.java:167)
	at burp.Zt2j.provideMenuItems(Unknown Source)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at burp.Zwun.invoke(Unknown Source)
	at jdk.proxy2/jdk.proxy2.$Proxy16.provideMenuItems(Unknown Source)
	at burp.Znzr.ZB(Unknown Source)
	at burp.Zzgo.ZG(Unknown Source)
	at burp.Zj71.ZL(Unknown Source)
	at burp.Zj71.ZS(Unknown Source)
	at burp.Zj71.Zc(Unknown Source)
	at burp.Zj71.ZI(Unknown Source)
	at burp.Zj71.ZB(Unknown Source)
	at burp.Zw6y.ZV(Unknown Source)
	at burp.Zzu9.ZT(Unknown Source)
	at burp.Zzu9.ZS(Unknown Source)
	at burp.Zzty.ZT(Unknown Source)
	at burp.Zw4l.Zs(Unknown Source)
	at burp.Z_xn.menuSelected(Unknown Source)
	at java.desktop/javax.swing.JMenu.fireMenuSelected(JMenu.java:1046)
	at java.desktop/javax.swing.JMenu$MenuChangeListener.stateChanged(JMenu.java:1126)
	at java.desktop/javax.swing.DefaultButtonModel.fireStateChanged(DefaultButtonModel.java:352)
	at java.desktop/javax.swing.DefaultButtonModel.setSelected(DefaultButtonModel.java:234)
	at java.desktop/javax.swing.JMenu.setSelected(JMenu.java:301)
	at java.desktop/com.apple.laf.ScreenMenu$2.run(ScreenMenu.java:142)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:308)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by kgmhk** [comment]
Hi @summitt 
I tried removing Nope extension and ~/.NoPEProxy directory.
After that installing NoPEProxy from the Burp Store (BApp Store), But it still doesn't show up. 😢

**Comment by summitt** [comment]
Still trying to reproduce. Are you running the ARM or Intel version of Burp. I've noticed lots of unexpected issues running the ARM version. The intel version runs fine on my M1.

**Comment by summitt** [comment]
I just released a new version that fixes many issues on the M1 Macs. Try it out and let me know if this fixes your issues
https://github.com/summitt/Burp-Non-HTTP-Extension/releases/tag/v1.7

**Comment by oliv10** [comment]
This update solved the issue that I was having where the tab did not show up. :)
