### ISSUE TITLE
What java version does it support?

### ISSUE THREAD

**Issue by tosiara** [summitt/Burp-Non-HTTP-Extension#9]
I run Burp on:

```
# cat /etc/issue
Kali GNU/Linux 2.0 \n \l

# uname -a
Linux burpbox 4.0.0-kali1-686-pae #1 SMP Debian 4.0.4-1+kali2 (2015-06-03) i686 GNU/Linux

# java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-1~deb8u1)
OpenJDK Server VM (build 24.79-b02, mixed mode)
```

And get this when loading extension:

```
java.lang.UnsupportedClassVersionError: burp/BurpExtender : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:274)
    at burp.mdh.a(Unknown Source)
    at burp.mdh.<init>(Unknown Source)
    at burp.w6f.a(Unknown Source)
    at burp.n1d.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:745)
```

What versions of java are supported?

**Comment by summitt** [comment]
i think all my machines are java 8. i'll try kali later and see if i can
reproduce the issue.

**Comment by tosiara** [comment]
Could you post instructions on wiki how to compile extension using local JDK? Thanks

**Comment by summitt** [comment]
you should be able to use egit in eclipse to pull the project into eclipse
directly from github then convert to a maven project. ideally that should
be it but it's never that simple :).

**Comment by summitt** [comment]
I just checked my code and you will need java 8 even if you try to compile locally. Your quickest option would be to install java 1.8 on kali. Otherwise your going to have to go through the steps to set up the dev env and patch my code to use java 1.7 libraries for some of the methods. 

Here is how to install java8 on kali.
https://forums.kali.org/showthread.php?20808-Install-Java-8-on-Kali-Linux
